version: "0.5"
is_strict: true

# NOTE: Elevated processes (is_elevated: true) run via sudo, which does not
# preserve environment variables. We must explicitly pass needed variables
# inline in the command for them to be available in elevated scripts.

processes:
  InitNamespaces:
    is_elevated: true
    command: |
      RATE_UP_TO_N0="${RATE_UP_TO_N0}" \
      DELAY_UP_TO_N0="${DELAY_UP_TO_N0}" \
      RATE_N0_TO_UP="${RATE_N0_TO_UP}" \
      DELAY_N0_TO_UP="${DELAY_N0_TO_UP}" \
      RATE_N0_TO_DOWN="${RATE_N0_TO_DOWN}" \
      DELAY_N0_TO_DOWN="${DELAY_N0_TO_DOWN}" \
      RATE_DOWN_TO_N0="${RATE_DOWN_TO_N0}" \
      DELAY_DOWN_TO_N0="${DELAY_DOWN_TO_N0}" \
      IP_UPSTREAM_NODE="${IP_UPSTREAM_NODE}" \
      IP_NODE0="${IP_NODE0}" \
      IP_DOWNSTREAM_NODE="${IP_DOWNSTREAM_NODE}" \
      bash "${SOURCE_DIR}/scripts/init-namespaces.sh"

  PrepareUpstreamNode:
    command: bash "${SOURCE_DIR}/scripts/prepare-upstream-node.sh"
    depends_on:
      InitNamespaces:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"

  UpstreamNode:
    is_elevated: true
    command: |
      UPSTREAM_NODE_DIR="${UPSTREAM_NODE_DIR}" \
      REF_SLOT="${REF_SLOT}" \
      ONSET_OF_REF_SLOT="${ONSET_OF_REF_SLOT}" \
      PORT_UPSTREAM_NODE="${PORT_UPSTREAM_NODE}" \
      ip netns exec leios-experiment:upstream bash "${SOURCE_DIR}/scripts/upstream-node.sh"
    log_location: "${WORKING_DIR}/upstream-node.log"
    depends_on:
      PrepareUpstreamNode:
        condition: process_completed_successfully
    availability:
      restart: "always"

  PrepareNode0:
    is_elevated: true
    command: |
      NODE0_DIR="${NODE0_DIR}" \
      DATA_DIR="${DATA_DIR}" \
      PORT_UPSTREAM_NODE="${PORT_UPSTREAM_NODE}" \
      IP_UPSTREAM_NODE="${IP_UPSTREAM_NODE}" \
      bash "${SOURCE_DIR}/scripts/prepare-node0.sh"
    depends_on:
      InitNamespaces:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"

  Node0:
    is_elevated: true
    command: |
      NODE0_DIR="${NODE0_DIR}" \
      PORT_NODE0="${PORT_NODE0}" \
      ip netns exec leios-experiment:node0 bash "${SOURCE_DIR}/scripts/node0.sh"
    log_location: "${WORKING_DIR}/node0.log"
    depends_on:
      PrepareNode0:
        condition: process_completed_successfully
    availability:
      restart: "always"

  PrepareDownstreamNode:
    is_elevated: true
    command: |
      DOWNSTREAM_NODE_DIR="${DOWNSTREAM_NODE_DIR}" \
      DATA_DIR="${DATA_DIR}" \
      PORT_NODE0="${PORT_NODE0}" \
      IP_NODE0="${IP_NODE0}" \
      bash "${SOURCE_DIR}/scripts/prepare-downstream-node.sh"
    depends_on:
      InitNamespaces:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"

  DownstreamNode:
    is_elevated: true
    command: |
      DOWNSTREAM_NODE_DIR="${DOWNSTREAM_NODE_DIR}" \
      PORT_DOWNSTREAM_NODE="${PORT_DOWNSTREAM_NODE}" \
      ip netns exec leios-experiment:downstream bash "${SOURCE_DIR}/scripts/downstream-node.sh"
    log_location: "${WORKING_DIR}/downstream-node.log"
    depends_on:
      PrepareDownstreamNode:
        condition: process_completed_successfully
    availability:
      restart: "always"

  SSOnUpstreamNode:
    is_elevated: true
    command: |
      IP_UPSTREAM_NODE="${IP_UPSTREAM_NODE}" \
      PORT_UPSTREAM_NODE="${PORT_UPSTREAM_NODE}" \
      PORT_NODE0="${PORT_NODE0}" \
      ip netns exec leios-experiment:upstream bash "${SOURCE_DIR}/scripts/ss-on-upstream.sh"
    depends_on:
      UpstreamNode:
        condition: "process_started"
    availability:
      restart: "always"

  SSOnNode0:
    is_elevated: true
    command: |
      IP_NODE0="${IP_NODE0}" \
      PORT_NODE0="${PORT_NODE0}" \
      PORT_UPSTREAM_NODE="${PORT_UPSTREAM_NODE}" \
      PORT_DOWNSTREAM_NODE="${PORT_DOWNSTREAM_NODE}" \
      ip netns exec leios-experiment:node0 bash "${SOURCE_DIR}/scripts/ss-on-node0.sh"
    depends_on:
      Node0:
        condition: "process_started"
    availability:
      restart: "always"

  SSOnDownstreamNode:
    is_elevated: true
    command: |
      IP_DOWNSTREAM_NODE="${IP_DOWNSTREAM_NODE}" \
      PORT_NODE0="${PORT_NODE0}" \
      PORT_DOWNSTREAM_NODE="${PORT_DOWNSTREAM_NODE}" \
      ip netns exec leios-experiment:downstream bash "${SOURCE_DIR}/scripts/ss-on-downstream.sh"
    depends_on:
      DownstreamNode:
        condition: "process_started"
    availability:
      restart: "always"

  Analyze:
    command: |
      set -exuo pipefail;
      while true; do
        sleep 1
        python "${SOURCE_DIR}/analyse.py" \
          "$REF_SLOT" "$ONSET_OF_REF_SLOT" \
          "$UPSTREAM_NODE_DIR/schedule.json" \
          "$WORKING_DIR/upstream-node.log" \
          "$WORKING_DIR/node0.log" \
          "$WORKING_DIR/downstream-node.log" \
          "$WORKING_DIR/scatter_plot.png"
      done;

    log_location: "${WORKING_DIR}/analyse.log"
    depends_on:
      UpstreamNode:
        condition: process_started
      Node0:
        condition: process_started
      DownstreamNode:
        condition: process_started
    availability:
      restart: "always"
