config.schema.json: config.d.ts
	npx typescript-json-schema config.d.ts Config > config.schema.json

topology.schema.json: topology.d.ts
	npx typescript-json-schema topology.d.ts Topology > topology.schema.json
