version: "0.5"
is_strict: true

processes:
  Init:
    command: |
      set -u
      bash "${SOURCE_DIR}/scripts/init.sh"
    availability:
      restart: "on_failure"

  Node1:
    environment:
      - NODE_ID=1
    command: bash "${SOURCE_DIR}/scripts/run-node.sh"
    log_location: "${WORKING_DIR}/node1/node.log"
    depends_on:
      Init:
        condition: process_completed_successfully
    availability:
      restart: "always"

  Node2:
    environment:
      - NODE_ID=2
    command: bash "${SOURCE_DIR}/scripts/run-node.sh"
    log_location: "${WORKING_DIR}/node2/node.log"
    depends_on:
      Init:
        condition: process_completed_successfully
    availability:
      restart: "always"

  Node3:
    environment:
      - NODE_ID=3
    command: bash "${SOURCE_DIR}/scripts/run-node.sh"
    log_location: "${WORKING_DIR}/node3/node.log"
    depends_on:
      Init:
        condition: process_completed_successfully
    availability:
      restart: "always"

  TxGenerator:
    command: tx-generator -- json_highlevel ${SOURCE_DIR}/gen.json
    depends_on:
      Node1:
        condition: process_started
      Node2:
        condition: process_started
      Node3:
        condition: process_started
    availability:
      restart: "on_failure"
