version: "0.5"
is_strict: true

processes:
  Init:
    command: |
      bash "${SCRIPTS:-scripts}/init.sh"
    availability:
      restart: "on_failure"

  Node1:
    environment:
      - NODE_ID=1
    command: |
      bash "${SCRIPTS:-scripts}/run-node.sh"
    log_location: "${WORKING_DIR:-devnet}/node1/node.log"
    depends_on:
      Init:
        condition: process_completed_successfully
    availability:
      restart: "always"

  Node2:
    environment:
      - NODE_ID=2
    command: |
      bash "${SCRIPTS:-scripts}/run-node.sh"
    log_location: "${WORKING_DIR:-devnet}/node2/node.log"
    depends_on:
      Init:
        condition: process_completed_successfully
    availability:
      restart: "always"

  Node3:
    environment:
      - NODE_ID=3
    command: |
      bash "${SCRIPTS:-scripts}/run-node.sh"
    log_location: "${WORKING_DIR:-devnet}/node3/node.log"
    depends_on:
      Init:
        condition: process_completed_successfully
    availability:
      restart: "always"
