#!/usr/bin/env python3

"""
Translate trace log files generated by the Praos node into log files
in the format expected by the Leios trace verifier.
"""

import json, sys
from datetime import datetime, timezone

def log_message(message, time):
    print(json.dumps({"message": message, "time_s": time.total_seconds()}))

fmt = "%Y-%m-%dT%H:%M:%S.%fZ"
last_at = None
last_SLC_slot = None

for line in sys.stdin:
    try:
        obj = json.loads(line)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        exit(127)

    if last_at is None:
        last_at = obj['at']

    curr_at = obj['at']
    time = datetime.strptime(curr_at, fmt).replace(tzinfo=timezone.utc) \
           -                                                            \
           datetime.strptime(last_at, fmt).replace(tzinfo=timezone.utc)
    last_at = curr_at

    if obj['ns'] == "Forge.Loop.AdoptedBlock":
        message = {
            "type":             "RBGenerated",
            "producer":         obj['host'],
            "slot":             last_SLC_slot,
            "id":               obj['data']['blockHash'],
            "endorsement":      None,
            "parent":           None, # FIXME: This is not available
            "size":             obj['data']['blockSize'],
            "tx_payload_bytes": None, # FIXME: This is not available
            }
    elif obj['ns'] == "BlockFetch.Client.CompletedBlockFetch":
        message = {
            "type":      "RBReceived",
            "recipient": obj['host'],
            "id":        obj['data']['block']
            }
    else:
        if obj['ns'] == "Forge.Loop.StartLeadershipCheck":
            if last_SLC_slot is None:
                last_SLC_slot = obj['data']['slot']
            else:
                message = {
                    "type": "Slot",
                    "node": obj['host'],
                    "slot": last_SLC_slot
                    }
                log_message(message, time)
                last_SLC_slot = obj['data']['slot']
        continue

    log_message(message, time)
