# yaml-language-server: $schema=./config.schema.json

################################################################################
# Configuration for least realistic simulation
################################################################################

relay-strategy: "request-from-all"
tcp-congestion-control: false
multiplex-mini-protocols: false
treat-blocks-as-full: true
leios-stage-active-voting-slots: 20
leios-vote-send-recv-stages: true