nodes = [
    # producers
    { location = [-80, 40], stake = 1000000 },
    { location = [0, 10], stake = 1000000 },
    { location = [70, 40], stake = 1000000 },
    { location = [80, 100], stake = 1000000 },
    { location = [-30, 170], stake = 10000000 },
    # relays
    { location = [-60, 60] },
    { location = [0, 30] },
    { location = [40, 60] },
    { location = [50, 70] },
    { location = [55, 90] },
    { location = [30, 140] },
    { location = [-30, 140] },
    { location = [-70, 100] },
]

[[links]]
nodes = [0, 5]
latency_ms = 11

[[links]]
nodes = [1, 6]
latency_ms = 10

[[links]]
nodes = [2, 7]
latency_ms = 17

[[links]]
nodes = [2, 8]
latency_ms = 13

[[links]]
nodes = [3, 9]
latency_ms = 13

[[links]]
nodes = [4, 11]
latency_ms = 13

[[links]]
nodes = [5, 6]
latency_ms = 34

[[links]]
nodes = [5, 11]
latency_ms = 32

[[links]]
nodes = [5, 12]
latency_ms = 10

[[links]]
nodes = [6, 8]
latency_ms = 32

[[links]]
nodes = [6, 9]
latency_ms = 39

[[links]]
nodes = [6, 10]
latency_ms = 57

[[links]]
nodes = [6, 12]
latency_ms = 44

[[links]]
nodes = [7, 9]
latency_ms = 13

[[links]]
nodes = [7, 11]
latency_ms = 54

[[links]]
nodes = [8, 9]
latency_ms = 7

[[links]]
nodes = [8, 12]
latency_ms = 65

[[links]]
nodes = [9, 10]
latency_ms = 23

[[links]]
nodes = [9, 11]
latency_ms = 51

[[links]]
nodes = [10, 11]
latency_ms = 32

[[links]]
nodes = [11, 12]
latency_ms = 24
