{
 "title": "Call Trace",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {}
   },
   {
    "name": "name",
    "query": {}
   },
   {
    "name": "thread",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Max Duration by Thread & Call Stack [5m window]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by(thread, stack) (\n  max_over_time(\n    {service=\"call-trace\", instance=~\"$instance\", name=~\"$name\", thread=~\"$thread\"} \n      | json\n      | event=\"End\"\n      | unwrap duration [5m]\n  )\n)",
     "legendFormat": "[{{thread}}] $ {{stack}}"
    }
   ]
  },
  {
   "title": "Average Duration by Thread & Call Stack [5m window]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by(thread, stack) (\n  avg_over_time(\n    {service=\"call-trace\", instance=~\"$instance\", name=~\"$name\", thread=~\"$thread\"}\n      | json\n      | event=\"End\"\n      | unwrap duration [5m]\n  )\n)",
     "legendFormat": "[{{thread}}] $ {{stack}}"
    }
   ]
  },
  {
   "title": "Max Allocations by Thread & Call Stack [5m window]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by(thread, stack) (\n  max_over_time(\n    {service=\"call-trace\", instance=~\"$instance\", name=~\"$name\", thread=~\"$thread\"} \n      | json\n      | event=\"End\"\n      | unwrap allocations [5m]\n  )\n)",
     "legendFormat": "[{{thread}}] $ {{stack}}"
    }
   ]
  },
  {
   "title": "Average Allocations by Thread & Call Stack [5m window]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by(thread, stack) (\n  avg_over_time(\n    {service=\"call-trace\", instance=~\"$instance\", name=~\"$name\", thread=~\"$thread\"} \n      | json\n      | event=\"End\"\n      | unwrap allocations [5m]\n  )\n)",
     "legendFormat": "[{{thread}}] $ {{stack}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"call-trace\", instance=~\"$instance\", name=~\"$name\", thread=~\"$thread\"} | json",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "traces",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"call-trace\", instance=~\"$instance\", thread=~\"$thread\"} \n  | json\n  | event=\"End\"\n  | label_format root_id=`{{ regexReplaceAll \"^([0-9]+).*\" .id \"${1}\" }}`\n  # Span fields\n  | label_format operationName=`{{ .name }}`\n  | label_format duration_sec=`{{ .duration }}`\n  | label_format serviceName=`{{ .instance }} - {{ .thread }}`\n  | label_format spanID=`{{ .instance }} - {{ .thread }} - {{ .id }}`\n  | label_format parentSpanID=`{{ .instance }} - {{ .thread }} - {{ .parent_id }}`\n  | label_format traceID=`{{ .instance }} - {{ .thread }} - {{ .root_id }}`\n  | keep traceID, spanID, parentSpanID, operationName, duration_sec, serviceName"
    }
   ]
  }
 ]
}