{
 "title": "Cardano Leios - Forging",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ForgedBlock events",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service=\"cardano-node\", ns=\"Forge.Loop.ForgedBlock\"} |= ``"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_mempoolBytes_int{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_txsInMempool_int{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Leadership Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total Wins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_node_is_leader_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ranking Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true
  },
  {
   "title": "Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_xu_memory_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_xu_memory_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_xu_time_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_xu_time_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Ref Script Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_ref_script_size_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_ref_script_size_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Endorser Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_count_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_xu_memory_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_xu_memory_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_xu_time_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_xu_time_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Tx Ref Script Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_ref_script_size_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"})",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_ref_script_size_bytes_counter{job=\"integrations/cardano-node\", environment=\"leios\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}