{
 "title": "Proto DevNet - Leios Voting",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rbHash",
    "query": {
     "query": "label_values(leios_votes_acquired_total,rbHash)"
    }
   },
   {
    "name": "voterId",
    "query": {
     "query": "label_values(leios_votes_acquired_total,voterId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total acquired votes per voterId",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(voterId) (count_over_time({service=\"leios-voting\", rbHash=~\"$rbHash\", voterId=~\"$voterId\"} | kind = `LeiosVoteAcquired` [5s]))",
     "legendFormat": "{{voterId}}"
    }
   ]
  },
  {
   "title": "Total acquired votes per rbHash",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(rbHash) (count_over_time({service=\"leios-voting\", rbHash=~\"$rbHash\", voterId=~\"$voterId\"} | kind = `LeiosVoteAcquired` [5s]))",
     "legendFormat": "{{voterId}}"
    }
   ]
  },
  {
   "title": "Acquired votes",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"leios-voting\", rbHash=~\"$rbHash\", voterId=~\"$voterId\"}"
    }
   ]
  }
 ]
}