{
 "title": "Proto DevNet - Forging",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "ForgedBlock events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{type=\"cardano-node\", ns=\"Forge.Loop.ForgedBlock\"} |= ``"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_mempoolBytes_int{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_mempoolBytes_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_txsInMempool_int{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Leadership Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Wins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_node_is_leader_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Ranking Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_count_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_count_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_count_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_count_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_bytes_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_bytes_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_xu_memory_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_xu_memory_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_xu_time_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_xu_time_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Ref Script Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_ranking_block_total_tx_ref_script_size_bytes_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_ranking_block_total_tx_ref_script_size_bytes_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Endorser Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_count_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_count_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_count_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_count_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_bytes_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_bytes_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_xu_memory_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_xu_memory_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_xu_time_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_xu_time_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Tx Ref Script Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cardano_node_metrics_Forge_endorser_block_total_tx_ref_script_size_bytes_counter{ })",
     "legendFormat": "sum"
    },
    {
     "expr": "cardano_node_metrics_Forge_endorser_block_total_tx_ref_script_size_bytes_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}