{
 "title": "Proto Devnet - PTrace",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({type=\"ptrace\"},process)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Started/Ended/Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(ptrace_started_total{process=~\"$host\"})",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(ptrace_ended_total{process=~\"$host\"})",
     "legendFormat": "Ended"
    },
    { "expression": "$Started - $Ended\n", "type": "math" }
   ]
  },
  {
   "title": "Sum Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ptrace_duration_total_s{process=~\"$host\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ptrace\", process=~\"$host\"} | json\n\n\n\n",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Duration by Thread & Call Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(ptrace_thread, ptrace_call_stack) (ptrace_duration_total_s{process=~\"$host\", ptrace_event=\"End\"})",
     "legendFormat": "[{{ptrace_thread}}] $ {{ptrace_call_stack}}"
    }
   ]
  },
  {
   "title": "Active by Thread & Call Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (ptrace_call_stack, ptrace_thread) (ptrace_started_total{process=~\"$host\"}) \n- \nsum by (ptrace_call_stack, ptrace_thread) (ptrace_ended_total{process=~\"$host\"})",
     "legendFormat": "[{{ptrace_thread}}] $ {{ptrace_call_stack}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "traces",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{kind=\"Process\", ptrace_event=\"End\", process=~\"$host\"}\n  | json spanID=\"call_id\", operationName=\"function\", duration_sec=\"duration\", serviceName=\"thread\", stack=\"call_id_stack\", argument=\"argument\", host=\"process\"\n  | label_format traceID=`{{ regexReplaceAll \"^([0-9]+).*\" .stack \"${1}\" }}`\n  | label_format parentSpanID=`{{ regexReplaceAll \".*(?:^|[^0-9])([0-9]+)[^0-9]+[0-9]+$\" .stack \"${1}\" }}`\n  | label_format parentSpanID=`{{ if eq .parentSpanID .spanID }}{{ \"\" }}{{ else }}{{ .parentSpanID }}{{ end }}`\n  | keep traceID, spanID, parentSpanID, operationName, duration_sec, serviceName, argument, host\n"
    }
   ]
  }
 ]
}