{
 "title": "Proto devnet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int / 1000",
     "legendFormat": "{{process}} mempool"
    },
    {
     "direction": "backward",
     "expr": "rate({service=\"tx-centrifuge\", ns=\"TxCentrifuge.Builder.NewTx\"}[30s]) * 204 / 1000",
     "legendFormat": "Load (assumed 204B per tx)"
    }
   ]
  },
  {
   "title": "Submission load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({service=\"tx-centrifuge\", ns=\"TxCentrifuge.Builder.NewTx\"}[30s])",
     "legendFormat": "tx/s"
    }
   ]
  },
  {
   "title": "Confirmed tx throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kBs" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_cumulativeTxBytes_int{job=\"cardano_node_metrics\"}[30s]) / 1000",
     "legendFormat": "{{alias}} txkB/s"
    }
   ]
  }
 ]
}