{
 "title": "Proto DevNet - Throughput",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{process=~\"$instance\"}",
     "legendFormat": "{{process}} mempool"
    },
    {
     "direction": "backward",
     "expr": "sum(sum_over_time({service=\"tx-firehose\", ns=\"TxFirehose.Submit.Success\"} | json size=\"size\" | unwrap size [30s])) / 30 / 1000",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Submission load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TxkB/s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(sum_over_time({service=\"tx-firehose\", ns=\"TxFirehose.Submit.Success\"} | json size=\"size\" | unwrap size [30s])) / 30 / 1000",
     "legendFormat": "accepted"
    },
    {
     "direction": "backward",
     "expr": "sum(sum_over_time({service=\"tx-firehose\", ns=\"TxFirehose.Submit.Reject\"} | json size=\"size\" | unwrap size [30s])) / 30 / 1000",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Confirmed tx throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "TxkB/s" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_cumulativeTxBytes_int{job=\"cardano_node_metrics\", process=~\"$instance\"}[300s])",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Time since last Leios certification or announcement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "last_over_time({service=\"cardano-node\", ns=\"Consensus.LeiosKernel.BlockAnnounced\", process=~\"$instance\"} | label_format ts=`{{ __timestamp__.UnixMilli }}` | unwrap ts [1h])",
     "legendFormat": "announced_ts"
    },
    {
     "direction": "backward",
     "expr": "last_over_time({service=\"cardano-node\", ns=\"Consensus.LeiosKernel.BlockCertified\", process=~\"$instance\"} | label_format ts=`{{ __timestamp__.UnixMilli }}` | unwrap ts [1h])",
     "legendFormat": "certified_ts"
    }
   ]
  },
  {
   "title": "Announcement age upon arrival",
   "type": "histogram",
   "gridPos": { "x": 0, "y": 16, "h": 8, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{kind=\"LeiosAnnouncementAccepted\"} | json age=\"announcementAgeSeconds\" | age != \"\"",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}