...@styles

title: {
  label: "RB Reference Approach (detailed)"
  near: top-center
  style.font-size: 24
  style.bold: true
  style.fill: "#ffffff"
  style.stroke: "#ffffff"
}

stable: {
  label: "Stable chain prefix"
  class: container

  RBs: {
    class: rb_stacked
    label: "[RB]\n(genesis, tip-k-2)"
  }

  RB: {
    class: rb
    label: "RB\n(tip-k-1)"
  }
}

volatile: {
  label: "Volatile chain suffix"
  class: container

  RBs: {
    class: rb_stacked
    label: "[RB]\n(tip-k, tip-2)"
  }

  RB1: {
    class: rb
    label: "RB\n(tip-1)"
  }

  RB: {
    class: rb
    label: "RB\n(tip)"
  }
}

RB0: {
  class: rb_unconfirmed
  label: "RB"
}

# Most secure, highest latency

secure: {
  label: "Most secure, highest latency"
  class: container

  EB: {
    class: eb
    label: "EB"
  }

  IB: {
    class: ib_stacked
    label: "IB"
  }
}

fast: {
  label: "Lowest latency, least secure"
  class: container

  EB: {
    class: eb
    label: "EB"
  }
  IB: {
    class: ib_stacked
    label: "IB"
  }
}

# Links

# Stable chain prefix
stable.RB -> stable.RBs: {
  class: to_rb_arrow
}

# Volatile chain suffix
volatile.RB -> volatile.RB1: {
  class: to_rb_arrow
}
volatile.RB1 -> volatile.RBs: {
  class: to_rb_arrow
}
volatile.RBs -> stable.RB: {
  class: to_rb_arrow
}
RB0 -> volatile.RB: {
  class: to_rb_arrow
  style: {
    stroke-dash: 7
  }
}

RB0 -> secure.EB: "Contains\nEB certificate" {
  class: eb_cert
}

RB0 -> fast.EB: "Contains\nEB certificate" {
  class: eb_cert
}

# EB links

secure.EB -> secure.IB: "Ref(s)" {
  class: to_ib_arrow
}

fast.EB -> fast.IB: "Ref(s)" {
  class: to_ib_arrow
}

# IB links

secure.IB -> stable.RB: "Ref" {
  class: to_rb_arrow
}

fast.IB -> volatile.RB: "Ref" {
  class: to_rb_arrow
}

direction: left
