classes: {
  rb: {
    style: {
      stroke: "#6A9BC7"
      fill: "#B0E2FF"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
    }
  }
  rb_stacked: {
    style: {
      stroke: "#6A9BC7"
      fill: "#B0E2FF"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
      multiple: true
    }
  }
  rb_unconfirmed: {
    style: {
      stroke: "#6A9BC7"
      fill: "#D0F0FF"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
      stroke-dash: 7
    }
  }
  eb: {
    style: {
      stroke: "#D4A76A"
      fill: "#FFE4C4"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
    }
  }
  ib: {
    style: {
      stroke: "#D4C76A"
      fill: "#FFFACD"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
    }
  }
  ib_stacked: {
    style: {
      stroke: "#D4C76A"
      fill: "#FFFACD"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
      multiple: true
    }
  }
  container: {
    style: {
      stroke: "#dedede"
      fill: "#f5f5f5"
      font-color: "#666666"
      font-size: 16
      border-radius: 8
    }
  }
  to_rb_arrow: {
    style: {
      stroke: "#6A9BC7"
    }
  }
  eb_cert: {
    style: {
      stroke: "#D4A76A"
      stroke-dash: 7
    }
  }
  to_eb_arrow: {
    style: {
      stroke: "#D4A76A"
    }
  }
  to_ib_arrow: {
    style: {
      stroke: "#D4C76A"
    }
  }
}
