classes: {
  rb: {
    style: {
      stroke: "#2a2a2a"
      fill: "#B0E2FF"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
    }
  }
  rb_stacked: {
    style: {
      stroke: "#2a2a2a"
      fill: "#B0E2FF"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
      multiple: true
    }
  }
  eb: {
    style: {
      stroke: "#aaaaaa"
      fill: "#FFE4C4"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
    }
  }
  ib: {
    style: {
      stroke: "#aaaaaa"
      fill: "#FFFACD"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
    }
  }
  ib_stacked: {
    style: {
      stroke: "#aaaaaa"
      fill: "#FFFACD"
      font-color: "#2a2a2a"
      font-size: 16
      border-radius: 10
      multiple: true
    }
  }
  container: {
    style: {
      stroke: "#dedede"
      fill: "#f5f5f5"
      font-color: "#666666"
      font-size: 16
      border-radius: 8
    }
  }
  rb_arrow: {
    style: {
      stroke: "#2a2a2a"
    }
  }
  eb_cert: {
    style: {
      stroke: "#2a2a2a"
      stroke-dash: 7
    }
  }
  eb_arrow: {
    style: {
      stroke: "#aaaaaa"
    }
  }
  ib_arrow: {
    style: {
      stroke: "#aaaaaa"
    }
  }
}
