# yaml-language-server: $schema=./config.schema.json

################################################################################
# Configuration for least realistic simulation
################################################################################

relay-strategy: "request-from-first"
tcp-congestion-control: true
multiplex-mini-protocols: true
treat-blocks-as-full: true
ib-diffusion-order: "freshest-first"
