module PraosProtocol.Common.AnchoredFragment (
  module Ouroboros.Network.AnchoredFragment,
) where

import Ouroboros.Network.AnchoredFragment (
  Anchor (..),
  AnchoredFragment,
  AnchoredSeq (..),
  ChainUpdate (..),
  HasHeader (..),
  Point (..),
  addBlock,
  anchorBlockNo,
  anchorFromBlock,
  anchorFromPoint,
  anchorIsGenesis,
  anchorNewest,
  anchorPoint,
  anchorToBlockNo,
  anchorToHash,
  anchorToHeaderFields,
  anchorToPoint,
  anchorToSlotNo,
  anchorToTip,
  applyChainUpdate,
  applyChainUpdates,
  blockPoint,
  castAnchor,
  castPoint,
  dropNewest,
  dropWhileNewest,
  filter,
  filterWithStop,
  filterWithStopSpec,
  findFirstPoint,
  fromNewestFirst,
  fromOldestFirst,
  head,
  headAnchor,
  headBlockNo,
  headHash,
  headPoint,
  headSlot,
  intersect,
  intersectionPoint,
  isPrefixOf,
  join,
  last,
  lastPoint,
  lastSlot,
  length,
  mapAnchoredFragment,
  null,
  pointOnFragment,
  pointOnFragmentSpec,
  prettyPrint,
  rollback,
  selectPoints,
  selectPointsSpec,
  sliceRange,
  splitAfterPoint,
  splitAt,
  splitAtSlot,
  splitBeforePoint,
  successorBlock,
  takeOldest,
  takeWhileOldest,
  toNewestFirst,
  toOldestFirst,
  valid,
  validExtension,
  withinFragmentBounds,
 )
