#!/usr/bin/env bash
#
# Re-create the burst demo's Praos block snapshot on top of a Dijkstra-enabled
# (Leios-capable) cardano-node by running the proto-devnet for long enough to
# forge a target number of blocks, then harvesting node1's immutable DB and
# genesis files into a new dated snapshot directory next to the existing one.
#
# Why: the burst demo ships a Conway-era immutable DB and matching genesis
# files, generated by an older P&T pipeline. After the Leios prototype was
# rebased onto upstream main + a Dijkstra hard fork, our cardano-node refuses
# to start without DijkstraGenesisFile + TestDijkstraHardForkAtEpoch. This
# script produces a drop-in Dijkstra replacement.
#
# Output:
#   demo/burst/data/<YYYY-MM-DD-HH-MM>-proto-devnet/
#     immutable.tar.gz                   -- harvested immutable DB
#     genesis/
#       genesis.byron.json
#       genesis.shelley.json
#       genesis.alonzo.json
#       genesis.conway.json
#       genesis.dijkstra.json            -- new in Dijkstra
#     summary.tsv                        -- one row per forged block:
#                                          slot, hash, node, announcing,
#                                          certifying. Both flags are 1/0,
#                                          parsed from the forging node's
#                                          'Consensus.LeiosKernel' trace —
#                                          announcing from the next observed
#                                          transition of praosState's
#                                          leiosStatePreviousAnnouncement
#                                          field, certifying from the
#                                          kernel's actual cert decision
#                                          ('EB downloaded ... and certified').
#
# Use summary.tsv to pick interesting REF_SLOTs for the demo (e.g. a slot
# right before/after an announcing or certifying block).
set -euo pipefail

: "${TARGET_BLOCKS:=15}"
: "${TIMEOUT_SECS:=600}"
: "${SOURCE_DIR:=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
: "${PROTO_DEVNET_DIR:=$(cd "$SOURCE_DIR/../proto-devnet" && pwd)}"

stamp="$(date +%Y-%m-%d-%H-%M)-proto-devnet"
OUT_DIR="$SOURCE_DIR/data/$stamp"

echo "Target blocks      : $TARGET_BLOCKS"
echo "Timeout            : ${TIMEOUT_SECS}s"
echo "proto-devnet dir   : $PROTO_DEVNET_DIR"
echo "Output snapshot    : $OUT_DIR"

# Prereqs that the proto-devnet run.sh also checks; we want them visible early.
for cmd in cardano-node cardano-cli process-compose tx-centrifuge sqlite3 jq yq envsubst tar db-immutaliser; do
  command -v "$cmd" >/dev/null || {
    echo "Missing: $cmd" >&2
    exit 1
  }
done

# Run proto-devnet in the background with TC + XRAY disabled (sandbox-friendly
# and avoids tc/sudo). WORKING_DIR is private to this run.
HARVEST_WORKDIR="$(mktemp -d -t burst-harvest-XXXXXX)"
trap 'rm -rf "$HARVEST_WORKDIR" 2>/dev/null || true' EXIT

(
  cd "$PROTO_DEVNET_DIR"
  export WORKING_DIR="$HARVEST_WORKDIR/devnet"
  export TC=0 XRAY=0 PC_DISABLE_TUI=1
  bash "$PROTO_DEVNET_DIR/run.sh"
) >"$HARVEST_WORKDIR/devnet.log" 2>&1 &
devnet_pid=$!

cleanup_devnet() {
  if kill -0 "$devnet_pid" 2>/dev/null; then
    echo "Stopping proto-devnet (pid $devnet_pid)..."
    kill -INT "$devnet_pid" 2>/dev/null || true
    wait "$devnet_pid" 2>/dev/null || true
  fi
  # SIGINT'ing the subshell doesn't always propagate to process-compose
  # (and from there to cardano-node), so we follow up by signalling them
  # directly. cardano-node needs a clean shutdown to flush the volatile
  # blocks to the immutable DB.
  pkill -INT -f "process-compose.*proto-devnet" 2>/dev/null || true
  pkill -INT -f "cardano-node run --config" 2>/dev/null || true
  # Wait (bounded) for cardano-node processes to exit so the immutable DB
  # is on disk before we tar it up.
  for _ in $(seq 1 30); do
    pgrep -f "cardano-node run --config" >/dev/null 2>&1 || break
    sleep 1
  done
  pkill -KILL -f "cardano-node run --config" 2>/dev/null || true
  pkill -KILL -f "process-compose.*proto-devnet" 2>/dev/null || true
}
trap 'cleanup_devnet; rm -rf "$HARVEST_WORKDIR" 2>/dev/null || true' EXIT

node1_sock="$HARVEST_WORKDIR/devnet/node1/node.socket"
export CARDANO_NODE_NETWORK_ID=164
export CARDANO_NODE_SOCKET_PATH="$node1_sock"

# Wait for the socket and the first block.
deadline=$(($(date +%s) + TIMEOUT_SECS))
echo -n "Waiting for node1 socket"
while [ ! -S "$node1_sock" ]; do
  [ "$(date +%s)" -gt "$deadline" ] && {
    echo " timed out"
    exit 1
  }
  sleep 1
  echo -n .
done
echo " up"

# Poll the tip until we've forged enough blocks.
echo "Forging blocks (target $TARGET_BLOCKS)..."
while :; do
  block=$(cardano-cli query tip 2>/dev/null | jq -r '.block // 0' || echo 0)
  printf '\r  block=%s' "$block"
  if [ "${block:-0}" -ge "$TARGET_BLOCKS" ]; then
    echo ""
    echo "Reached $block blocks; harvesting."
    break
  fi
  [ "$(date +%s)" -gt "$deadline" ] && {
    echo ""
    echo "Timed out at $block blocks"
    exit 1
  }
  sleep 2
done

# Stop the devnet so the immutable DB is flushed/closed.
cleanup_devnet

# Harvest node1's chain. Short proto-devnet runs leave all blocks in the
# VolatileDB (the immutable promotion lags by k blocks past the tip, and
# the volatile-to-immutable on-disk flush also requires more progress than
# a 15-block run produces). Use db-immutaliser to flatten node1's volatile
# chain into a fresh immutable DB that burst's immdb-server can serve.
src_node="$HARVEST_WORKDIR/devnet/node1"
src_genesis="$HARVEST_WORKDIR/devnet/genesis"
imm_work="$HARVEST_WORKDIR/immutaliser"

if [ ! -d "$src_node/db/volatile" ]; then
  echo "Expected volatile DB at $src_node/db/volatile, not found" >&2
  exit 1
fi

mkdir -p "$OUT_DIR/genesis" "$imm_work/immutable"
cp -r "$src_node/db/volatile" "$imm_work/volatile"
echo "Running db-immutaliser to flatten VolatileDB -> ImmutableDB"
db-immutaliser \
  --immutable-db "$imm_work/immutable" \
  --volatile-db "$imm_work/volatile" \
  --config "$src_node/config.yaml" \
  >"$HARVEST_WORKDIR/immutaliser.log" 2>&1 || {
  echo "db-immutaliser failed; tail of its log:" >&2
  tail -20 "$HARVEST_WORKDIR/immutaliser.log" >&2
  exit 1
}

echo "Packing $imm_work/immutable -> $OUT_DIR/immutable.tar.gz"
(cd "$imm_work" && tar -czf "$OUT_DIR/immutable.tar.gz" immutable)

# Copy + rename genesis files into the layout that burst's config.json
# expects (genesis.<era>.json, with a dot).
for era in byron shelley alonzo conway dijkstra; do
  cp -f "$src_genesis/${era}-genesis.json" "$OUT_DIR/genesis/genesis.${era}.json"
done

# Capture node1's Leios DB. The recorded Praos chain references EBs by
# header announcements/certificates; the upstream-node must serve those
# exact EB bodies so node0/downstream can resolve them when chain-syncing.
# Checkpoint the WAL into the main db first so a single file suffices.
if [ -f "$src_node/leios.db" ]; then
  echo "Checkpointing + harvesting $src_node/leios.db -> $OUT_DIR/leios.db"
  sqlite3 "$src_node/leios.db" "PRAGMA wal_checkpoint(TRUNCATE);" >/dev/null
  cp -f "$src_node/leios.db" "$OUT_DIR/leios.db"
else
  echo "Expected $src_node/leios.db, not found" >&2
  exit 1
fi

# Build summary.tsv from the three node logs. Columns:
#
#   slot         block slot
#   hash         block hash
#   node         forging node directory (node1/node2/node3)
#   announcing   1 iff the block included an EbAnnouncement in its Praos
#                header. Detected by walking the chain-wide kernel trace and
#                noting when 'leiosStatePreviousAnnouncement' changes to a
#                fresh 'Just ...': the announcement field of praosState is
#                "overwritten on every header tick", so the value seen at
#                praosStateLastSlot == S after a transition is the
#                announcement included in the block forged at slot S.
#   certifying   1 iff the kernel committed to a LeiosCert on this block
#                (i.e. emitted 'leiosDecideForgeTypePraos: EB downloaded ...
#                and certified LeiosCertificate ...' in the same forge cycle).
#                That's the *post-decision* signal, not the 'canCertify' bit
#                from the forge input.
echo "Writing $OUT_DIR/summary.tsv"
python3 - "$HARVEST_WORKDIR"/devnet/node[123]/node.log >"$OUT_DIR/summary.tsv" <<'PY'
import json, re, sys
from pathlib import Path

# (slot, hash, node) for every forged block; node = "node1"/"node2"/"node3".
forges = []
# Slots where the forging node's kernel decided to include a LeiosCert.
certifying = set()
# Slot -> announced EB hash, derived from kernel praosState transitions.
announcing = {}

# Match the embedded praosState in the kernel's 'called with' message.
# We pull out praosStateLastSlot and (optionally) the announcement hash.
KERNEL_RE = re.compile(
    r"praosStateLastSlot = At \(SlotNo (?P<slot>\d+)\)"
    r".*?leiosStatePreviousAnnouncement = "
    r"(?P<annc>Nothing|Just \(EbAnnouncement \{ebAnnouncementHash = (?P<hash>[0-9a-f]+))",
    re.DOTALL,
)

prev_annc_by_node = {}  # node -> last seen announcement hash, for change-detection

for path in (Path(p) for p in sys.argv[1:]):
    node = path.parent.name
    # Walk events sequentially so we can correlate cert decisions with the
    # ForgedBlock event that follows them within the same thread.
    pending_cert_by_thread = {}
    for raw in path.read_text().splitlines():
        try:
            outer = json.loads(raw)
            inner = json.loads(outer["message"])
        except Exception:
            continue
        ns = inner.get("ns", "")
        data = inner.get("data", {})
        thread = inner.get("thread")
        if ns == "Forge.Loop.ForgedBlock":
            slot = data.get("slot")
            h = (data.get("forgedBlock") or {}).get("newBlockHash")
            if slot is None or h is None:
                continue
            forges.append((slot, h, node))
            if pending_cert_by_thread.pop(thread, False):
                certifying.add(slot)
        elif ns == "Consensus.LeiosKernel.TraceLeiosKernel":
            msg = data.get("msg", "")
            if "and certified LeiosCertificate" in msg:
                pending_cert_by_thread[thread] = True
            elif msg.startswith("leiosDecideForgeTypePraos called with:"):
                m = KERNEL_RE.search(msg)
                if not m:
                    continue
                last_slot = int(m.group("slot"))
                annc = m.group("hash")  # None if praosState showed Nothing
                # Record an announcement only when it's a fresh value: the
                # praosStateLeiosAnnouncement field is overwritten every
                # header tick, so we only know a *new* announcement was made
                # if the value changed from what we saw before. Multiple
                # nodes will observe the same chain so any of them suffices.
                prev = prev_annc_by_node.get(node)
                if annc and annc != prev:
                    announcing[last_slot] = annc
                prev_annc_by_node[node] = annc

print("slot\thash\tnode\tannouncing\tcertifying")
for slot, h, node in sorted(forges):
    print(
        f"{slot}\t{h}\t{node}\t"
        f"{'1' if slot in announcing else '0'}\t"
        f"{'1' if slot in certifying else '0'}"
    )
PY

echo
echo "Snapshot written: $OUT_DIR"
echo
echo "Per-block summary:"
column -t -s $'\t' "$OUT_DIR/summary.tsv" | head -n 30
echo
echo "Next:"
echo "  1. Edit demo/burst/run.sh: set CLUSTER_RUN=\$DATA_DIR/$stamp"
echo "  2. Pick a REF_SLOT from summary.tsv (e.g. a certifying row's slot)."
echo "  3. Verify by running demo/burst/run.sh."
