name: "conformance"

on:
  pull_request:
    paths:
      - "leios-trace-hs/**"
      - "leios-trace-verifier/**"
  push:
    branches:
      - main
    paths:
      - "leios-trace-hs/**"
      - "leios-trace-verifier/**"

jobs:

  trace-verifier:
    name: Leios trace verifier
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
    - name: 🛠️ Install Nix
      uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-24.05
        install_url: https://releases.nixos.org/nix/nix-2.28.3/install
        extra_nix_config: |
          allowed-uris = ${{ env.ALLOWED_URIS }}
          trusted-public-keys = ${{ env.TRUSTED_PUBLIC_KEYS }}
          substituters = ${{ env.SUBSTITUTERS }}
          experimental-features = nix-command flakes
          accept-flake-config = true
    - name: 🏗️ Build trace verifier
      run: |
        nix build --show-trace .#leios-trace-verifier
    - name: 🏗️ Check example trace
      run: |
        nix run .#ols -- \
          sim leios \
          --leios-config-file data/simulation/config.default.yaml \
          --topology-file data/simulation/topo-default-100.yaml \
          --conformance-events \
          --shared-log-format JSON \
          --output-seconds 30 \
          --output-file sim.log
        nix run .#leios-trace-verifier -- \
          --config-file data/simulation/config.default.yaml \
          --topology-file data/simulation/topo-default-100.yaml \
          --trace-file sim.log \
          --idSut 0
